#!/bin/sh

# first
# This file look through all the files in the current
# directory for the string POSIX, and then prints the names of
# those files to the standard output.

trap 'echo Exiting: critical variable = $critical_variable' EXIT

set -o xtrace
for file in *
do
	if grep -q POSIX $file
	then
		echo $file
	fi
done
set +o xtrace

exit 0
